// resources/js/components/cart/CartComponent.vue
<template>
    <div>
        <div class="row" v-for="(cart, index) in carts">
            <div class="col-xl-3 border cart_product_img text-center p-2">
                <img :src="'img/' + cart.product.image" alt="Product" />
            </div>
            <div class="col-xl-2 border cart_product_name p-2">
                <a :href="'/product/' + cart.product.id"
                    ><h5>{{ cart.product.name }}</h5></a
                >
            </div>
            <div class="col-xl-2 border cart_product_price p-2">
                <h5>{{ cart.product.price }}</h5>
            </div>

            <div class="col-xl-2 border cart_product_price p-2">
                <h5>{{ cart.size.name }}</h5>
            </div>
            <div class="col-xl-2 border cart_product_price p-2">
                <h5>{{ cart.qty }}</h5>
            </div>
            <RemoveComponent
                :cartId="cart.id"
                :productId="cart.product.id"
                :sizeId="cart.size.id"
                :qty="cart.qty"
            />
        </div>

        <ClearComponent :carts="carts" />
    </div>
</template>

<script>
import axios from "axios";
import { cartNativeJsObj } from "../cartNativeJs";
import RemoveComponent from "./RemoveComponent.vue";
import ClearComponent from "./ClearComponent.vue";

export default {
    data: function () {
        return {
            carts: window.carts,
        };
    },
    components: {
        RemoveComponent,
        ClearComponent,
    },
    mounted() {
        console.log(window.carts);

        this.$store.subscribe((mutation, state) => {
            console.log(mutation.type);

            if (mutation.type == "setCarts")
                this.handleCart(this.$store.getters.getCarts); //!!!getter
        });
    },
    methods: {
        handleCart(carts) {
            this.carts = carts;
            cartNativeJsObj.selector = "#lblCartCount";

            cartNativeJsObj.changeValueSelector(carts.length);
        },
    },
};
</script>

// resources/js/components/cart/CartComponent.jsx
﻿import React from "react";
import ReactDOM from "react-dom";
import RemoveDialog from "./RemoveComponent";
import ClearDialog from "./ClearComponent";
import { store } from "../reducer";
import { cartNativeJsObj } from "../cartNativeJs";

class CartDialog extends React.Component {
    constructor(props) {
        super(props);
        this.handleCart = this.handleCart.bind(this);

        this.state = {
            carts: window.carts,
        };
    }

    componentDidMount() {
        console.log(this.state.carts);
        store.subscribe(() => this.handleStore(store.getState()));
    }

    handleStore(store) {
        this.handleCart(store.cartsReducer);
    }

    handleCart(carts) {
        this.setState({
            carts: carts,
        });
        // document.querySelector("#lblCartCount").innerText = carts.length;
        // cartNativeJsObj.countChange(carts.length);
        cartNativeJsObj.selector = "#lblCartCount";
        cartNativeJsObj.changeValueSelector(carts.length);
    }

    render() {
        return (
            <div>
                <div id="pannel">
                    {this.state.carts.map((item, key) => (
                        <div className="row" key={key}>
                            <div className="col-xl-3 border cart_product_img text-center p-2">
                                <img
                                    src={"/img/" + item.product.image}
                                    alt="Product"
                                />
                            </div>
                            <div className="col-xl-3 border cart_product_name p-2">
                                <a href={"/product/" + item.product.id}>
                                    <h3>{item.product.name}</h3>
                                </a>

                                {/* <h5>{item.product.name}</h5> */}
                            </div>{" "}
                            <div className="col-xl-2 border cart_product_price p-2">
                                <h5>{item.product.price}</h5>
                            </div>{" "}
                            <div className="col-xl-2 border cart_product_price p-2">
                                <h5>{item.size.name}</h5>
                            </div>
                            <div className="col-xl-2 border text-center p-5">
                                <RemoveDialog
                                    cartId={item.id}
                                    productId={item.product.id}
                                    sizeId={item.size.id}
                                    handleCart={this.handleCart}
                                />
                            </div>
                        </div>
                    ))}
                </div>
                <ClearDialog
                    handleCart={this.handleCart}
                    carts={this.state.carts}
                />
            </div>
        );
    }
}

const elem = document.querySelector(".cart_block");

if (elem) {
    ReactDOM.render(<CartDialog />, elem);
}
