// resources/js/components/cart/RemoveComponent.jsx
﻿import React from "react";
import axios from "axios";
import { store } from "../reducer";

export default class RemoveDialog extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            //..
        };
    }

    componentDidMount() {
        //...
    }

    removeCart(id, productId, sizeId) {
        let self = this; //!!!self - becouse axios
        axios
            .post("/clearone", {
                id: id,
                product_id: productId,
                size_id: sizeId,
            })
            .then(function (resp) {
                console.log(resp.data);

                self.handleCart(resp.data); //!!!self - becouse axios
            })
            .catch(function (resp) {
                console.log(resp); //!!!js-error

                if (resp.response) {
                    //!!!back-error
                    console.log(resp.response.data); //...message, ...file, ...line
                }
                alert("Could not delete cart");
            });
    }

    handleCart(carts) {
        // this.setState({
        //     carts: carts,
        // });

        // this.props.handleCart(carts); //!!!

        store.dispatch({ type: "CHANGE_STATE_CARTS", cartsAfterRemove: carts });
    }

    render() {
        return (
            <div>
                <a
                    className="btn btn-danger listbuttonremove"
                    href="#"
                    onClick={(e) => {
                        this.removeCart(
                            this.props.cartId,
                            this.props.productId,
                            this.props.sizeId
                        );
                        e.preventDefault();
                    }}
                >
                    <i className="fa fa-trash-o" aria-hidden="true"></i>
                </a>
            </div>
        );
    }
}

// resources/js/components/cart/RemoveComponent.vue
<template>
    <div class="col-xl-1 border text-center p-2">
        <button
            class="btn btn-danger listbuttonremove"
            id="cart.id"
            href="#"
            @click="removeCart(cartId, productId, sizeId, qty)"
        >
            <i class="fa fa-trash-o" aria-hidden="true"></i>
        </button>
    </div>
</template>

<script>
import axios from "axios";

export default {
    props: ["cartId", "productId", "sizeId", "qty"],
    data: function () {
        return {
            //...
        };
    },
    mounted() {
        //...
    },
    methods: {
        removeCart(id, productId, sizeId, qty) {
            event.preventDefault();
            let self = this; //!!!self - becouse axios
            axios
                .post("/clearone", {
                    id: id,
                    product_id: productId,
                    size_id: sizeId,
                    qty: qty,
                })
                .then(function (resp) {
                    console.log(resp.data);

                    // self.handleCart(resp.data); //!!!self - becouse axios
                    self.$store.commit("setCarts", resp.data);
                })
                .catch(function (resp) {
                    console.log(resp); //!!!js-error

                    if (resp.response) {
                        //!!!back-error
                        console.log(resp.response.data); //...message, ...file, ...line
                    }
                    alert("Could not delete cart");
                });
        },
    },
};
</script>
